export const Endpoints = {
    backend: "http://localhost:8080/api/",
    vetGetAll: `veterinarios`,
    vetGet: (id: number) => `veterinarios/${id}`,
    vetUpdate: (id: number) => `veterinarios/${id}`,
    vetCreate: `veterinarios`,
    vetDelete: (id: number) => `veterinarios/${id}`,
    donoGet: (id: number) => `donos/${id}`,
    donoGetAll: `donos`,
    donoUpdate: (id: number) => `donos/${id}`,
    donoDelete: (id: number) => `donos/${id}`,
    donoCreate: `donos`,
    petGet: (id: number) => `pets/${id}`,
    petGetAll: `pets`,
    petUpdate: (id: number) => `pets/${id}`,
    petDelete: (id: number) => `pets/${id}`,
    petCreate: `pets`,
    vacinaGet: (id: number) => `vacinas/${id}`,
    vacinaGetAll: `vacinas`,
    vacinaUpdate: (id: number) => `vacinas/${id}`,
    vacinaDelete: (id: number) => `vacinas/${id}`,
    vacinaCreate: `vacinas`,
    registroGet: (id: number) => `registros/${id}`,
    registroGetAll: `registros`,
    registroUpdate: (id: number) => `registros/${id}`,
    registroDelete: (id: number) => `registros/${id}`,
    registroCreate: `registros`
} as const;
